interface ZIF_I_MM_RES_C
  public .


  interfaces /BOBF/IF_LIB_CONSTANTS .

  constants:
    BEGIN OF SC_ACTION,
      BEGIN OF ZI_MM_RES,
 CREATE_ZI_MM_RES               TYPE /BOBF/ACT_KEY VALUE 'A6543B64103C1FE0A88C0127CD24B8A2',
 DELETE_ZI_MM_RES               TYPE /BOBF/ACT_KEY VALUE 'A6543B64103C1FE0A88C0127CD2538A2',
 LOCK_ZI_MM_RES                 TYPE /BOBF/ACT_KEY VALUE 'A6543B64103C1FE0A88C0127CD23F8A2',
 SAVE_ZI_MM_RES                 TYPE /BOBF/ACT_KEY VALUE 'A6543B64103C1FE0A88C0127CD25B8A2',
 UNLOCK_ZI_MM_RES               TYPE /BOBF/ACT_KEY VALUE 'A6543B64103C1FE0A88C0127CD2438A2',
 UPDATE_ZI_MM_RES               TYPE /BOBF/ACT_KEY VALUE 'A6543B64103C1FE0A88C0127CD24F8A2',
 VALIDATE_ZI_MM_RES             TYPE /BOBF/ACT_KEY VALUE 'A6543B64103C1FE0A88C0127CD2578A2',
      END OF ZI_MM_RES,
    END OF SC_ACTION .
  constants:
    BEGIN OF SC_ACTION_ATTRIBUTE,
        BEGIN OF ZI_MM_RES,
        BEGIN OF LOCK_ZI_MM_RES,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
 LEGACY_DAC_KEY                 TYPE STRING VALUE 'LEGACY_DAC_KEY',
        END OF LOCK_ZI_MM_RES,
        BEGIN OF UNLOCK_ZI_MM_RES,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
 LEGACY_DAC_KEY                 TYPE STRING VALUE 'LEGACY_DAC_KEY',
        END OF UNLOCK_ZI_MM_RES,
      END OF ZI_MM_RES,
    END OF SC_ACTION_ATTRIBUTE .
  constants:
    BEGIN OF SC_ALTERNATIVE_KEY,
      BEGIN OF ZI_MM_RES,
 DB_KEY                         TYPE /BOBF/OBM_ALTKEY_KEY VALUE 'A6543B64103C1FE0A88C0127CD2698A2',
      END OF ZI_MM_RES,
    END OF SC_ALTERNATIVE_KEY .
  constants:
    BEGIN OF SC_ASSOCIATION,
      BEGIN OF ZI_MM_RES,
 LOCK                           TYPE /BOBF/OBM_ASSOC_KEY VALUE 'A6543B64103C1FE0A88C0127CD23D8A2',
 MESSAGE                        TYPE /BOBF/OBM_ASSOC_KEY VALUE 'A6543B64103C1FE0A88C0127CD2398A2',
 PROPERTY                       TYPE /BOBF/OBM_ASSOC_KEY VALUE 'A6543B64103C1FE0A88C0127CD2498A2',
      END OF ZI_MM_RES,
      BEGIN OF ZI_MM_RES_LOCK,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE 'A6543B64103C1FE0A88C0127CD2618A2',
      END OF ZI_MM_RES_LOCK,
      BEGIN OF ZI_MM_RES_MESSAGE,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE 'A6543B64103C1FE0A88C0127CD25F8A2',
      END OF ZI_MM_RES_MESSAGE,
      BEGIN OF ZI_MM_RES_PROPERTY,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE 'A6543B64103C1FE0A88C0127CD2638A2',
      END OF ZI_MM_RES_PROPERTY,
    END OF SC_ASSOCIATION .
  constants:
    BEGIN OF SC_ASSOCIATION_ATTRIBUTE,
      BEGIN OF ZI_MM_RES,
        BEGIN OF PROPERTY,
 ALL_NODE_PROPERTY              TYPE STRING VALUE 'ALL_NODE_PROPERTY',
 ALL_NODE_ATTRIBUTE_PROPERTY    TYPE STRING VALUE 'ALL_NODE_ATTRIBUTE_PROPERTY',
 ALL_ASSOCIATION_PROPERTY       TYPE STRING VALUE 'ALL_ASSOCIATION_PROPERTY',
 ALL_ASSOCIATION_ATTRIBUTE_PROP TYPE STRING VALUE 'ALL_ASSOCIATION_ATTRIBUTE_PROP',
 ALL_ACTION_PROPERTY            TYPE STRING VALUE 'ALL_ACTION_PROPERTY',
 ALL_ACTION_ATTRIBUTE_PROPERTY  TYPE STRING VALUE 'ALL_ACTION_ATTRIBUTE_PROPERTY',
 ALL_QUERY_PROPERTY             TYPE STRING VALUE 'ALL_QUERY_PROPERTY',
 ALL_QUERY_ATTRIBUTE_PROPERTY   TYPE STRING VALUE 'ALL_QUERY_ATTRIBUTE_PROPERTY',
 ALL_SUBTREE_PROPERTY           TYPE STRING VALUE 'ALL_SUBTREE_PROPERTY',
        END OF PROPERTY,
      END OF ZI_MM_RES,
    END OF SC_ASSOCIATION_ATTRIBUTE .
  constants:
    SC_BO_KEY  TYPE /BOBF/OBM_BO_KEY VALUE 'A6543B64103C1FE0A88C0127CD22F8A2' .
  constants:
    SC_BO_NAME TYPE /BOBF/OBM_NAME VALUE 'ZI_MM_RES' .
  constants:
    BEGIN OF SC_DETERMINATION,
      BEGIN OF ZI_MM_RES,
 ACTION_AND_FIELD_CONTROL       TYPE /BOBF/DET_KEY VALUE 'A6543B64103C1FE0A88C0127CD26B8A2',
      END OF ZI_MM_RES,
    END OF SC_DETERMINATION .
  constants:
    BEGIN OF SC_GROUP,
 ZI_MM_RES                      TYPE /BOBF/OBM_GROUP_KEY VALUE 'A6543B64103C1FE0A88C012D6C4ED8A2',
    END OF SC_GROUP .
  constants:
    SC_MODEL_VERSION TYPE /BOBF/CONF_VERSION VALUE '00000' .
  constants:
    BEGIN OF SC_NODE,
 ZI_MM_RES                      TYPE /BOBF/OBM_NODE_KEY VALUE 'A6543B64103C1FE0A88C0127CD2338A2',
 ZI_MM_RES_LOCK                 TYPE /BOBF/OBM_NODE_KEY VALUE 'A6543B64103C1FE0A88C0127CD23B8A2',
 ZI_MM_RES_MESSAGE              TYPE /BOBF/OBM_NODE_KEY VALUE 'A6543B64103C1FE0A88C0127CD2378A2',
 ZI_MM_RES_PROPERTY             TYPE /BOBF/OBM_NODE_KEY VALUE 'A6543B64103C1FE0A88C0127CD2478A2',
    END OF SC_NODE .
  constants:
    BEGIN OF SC_NODE_ATTRIBUTE,
      BEGIN OF ZI_MM_RES,
  NODE_DATA                      TYPE STRING VALUE 'NODE_DATA',
  IDRES                          TYPE STRING VALUE 'IDRES',
  MATNR                          TYPE STRING VALUE 'MATNR',
  LOCID                          TYPE STRING VALUE 'LOCID',
  QTY_RES                        TYPE STRING VALUE 'QTY_RES',
  DATA                           TYPE STRING VALUE 'DATA',
  STATUS                         TYPE STRING VALUE 'STATUS',
      END OF ZI_MM_RES,
    END OF SC_NODE_ATTRIBUTE .
  constants:
    BEGIN OF SC_NODE_CATEGORY,
      BEGIN OF ZI_MM_RES,
 ROOT                           TYPE /BOBF/OBM_NODE_CAT_KEY VALUE 'A6543B64103C1FE0A88C0127CD2358A2',
      END OF ZI_MM_RES,
    END OF SC_NODE_CATEGORY .
  constants:
    BEGIN OF SC_VALIDATION,
      BEGIN OF ZI_MM_RES,
 ALTKEY_UNIQUENESS_CHECK        TYPE /BOBF/VAL_KEY VALUE 'A6543B64103C1FE0A88C0127CD26F8A2',
      END OF ZI_MM_RES,
    END OF SC_VALIDATION .
endinterface.
