interface ZIF_I_MM_MOV_C
  public .


  interfaces /BOBF/IF_LIB_CONSTANTS .

  constants:
    BEGIN OF SC_ACTION,
      BEGIN OF ZI_MM_MOV,
 CREATE_ZI_MM_MOV               TYPE /BOBF/ACT_KEY VALUE 'A6543B64103C1FE0A88BE93E2C1398A2',
 DELETE_ZI_MM_MOV               TYPE /BOBF/ACT_KEY VALUE 'A6543B64103C1FE0A88BE93E2C1418A2',
 LOCK_ZI_MM_MOV                 TYPE /BOBF/ACT_KEY VALUE 'A6543B64103C1FE0A88BE93E2C12D8A2',
 SAVE_ZI_MM_MOV                 TYPE /BOBF/ACT_KEY VALUE 'A6543B64103C1FE0A88BE93E2C1498A2',
 UNLOCK_ZI_MM_MOV               TYPE /BOBF/ACT_KEY VALUE 'A6543B64103C1FE0A88BE93E2C1318A2',
 UPDATE_ZI_MM_MOV               TYPE /BOBF/ACT_KEY VALUE 'A6543B64103C1FE0A88BE93E2C13D8A2',
 VALIDATE_ZI_MM_MOV             TYPE /BOBF/ACT_KEY VALUE 'A6543B64103C1FE0A88BE93E2C1458A2',
      END OF ZI_MM_MOV,
    END OF SC_ACTION .
  constants:
    BEGIN OF SC_ACTION_ATTRIBUTE,
        BEGIN OF ZI_MM_MOV,
        BEGIN OF LOCK_ZI_MM_MOV,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
 LEGACY_DAC_KEY                 TYPE STRING VALUE 'LEGACY_DAC_KEY',
        END OF LOCK_ZI_MM_MOV,
        BEGIN OF UNLOCK_ZI_MM_MOV,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
 LEGACY_DAC_KEY                 TYPE STRING VALUE 'LEGACY_DAC_KEY',
        END OF UNLOCK_ZI_MM_MOV,
      END OF ZI_MM_MOV,
    END OF SC_ACTION_ATTRIBUTE .
  constants:
    BEGIN OF SC_ALTERNATIVE_KEY,
      BEGIN OF ZI_MM_MOV,
 DB_KEY                         TYPE /BOBF/OBM_ALTKEY_KEY VALUE 'A6543B64103C1FE0A88BE93E2C1578A2',
      END OF ZI_MM_MOV,
    END OF SC_ALTERNATIVE_KEY .
  constants:
    BEGIN OF SC_ASSOCIATION,
      BEGIN OF ZI_MM_MOV,
 LOCK                           TYPE /BOBF/OBM_ASSOC_KEY VALUE 'A6543B64103C1FE0A88BE93E2C12B8A2',
 MESSAGE                        TYPE /BOBF/OBM_ASSOC_KEY VALUE 'A6543B64103C1FE0A88BE93E2C1278A2',
 PROPERTY                       TYPE /BOBF/OBM_ASSOC_KEY VALUE 'A6543B64103C1FE0A88BE93E2C1378A2',
      END OF ZI_MM_MOV,
      BEGIN OF ZI_MM_MOV_LOCK,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE 'A6543B64103C1FE0A88BE93E2C14F8A2',
      END OF ZI_MM_MOV_LOCK,
      BEGIN OF ZI_MM_MOV_MESSAGE,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE 'A6543B64103C1FE0A88BE93E2C14D8A2',
      END OF ZI_MM_MOV_MESSAGE,
      BEGIN OF ZI_MM_MOV_PROPERTY,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE 'A6543B64103C1FE0A88BE93E2C1518A2',
      END OF ZI_MM_MOV_PROPERTY,
    END OF SC_ASSOCIATION .
  constants:
    BEGIN OF SC_ASSOCIATION_ATTRIBUTE,
      BEGIN OF ZI_MM_MOV,
        BEGIN OF PROPERTY,
 ALL_NODE_PROPERTY              TYPE STRING VALUE 'ALL_NODE_PROPERTY',
 ALL_NODE_ATTRIBUTE_PROPERTY    TYPE STRING VALUE 'ALL_NODE_ATTRIBUTE_PROPERTY',
 ALL_ASSOCIATION_PROPERTY       TYPE STRING VALUE 'ALL_ASSOCIATION_PROPERTY',
 ALL_ASSOCIATION_ATTRIBUTE_PROP TYPE STRING VALUE 'ALL_ASSOCIATION_ATTRIBUTE_PROP',
 ALL_ACTION_PROPERTY            TYPE STRING VALUE 'ALL_ACTION_PROPERTY',
 ALL_ACTION_ATTRIBUTE_PROPERTY  TYPE STRING VALUE 'ALL_ACTION_ATTRIBUTE_PROPERTY',
 ALL_QUERY_PROPERTY             TYPE STRING VALUE 'ALL_QUERY_PROPERTY',
 ALL_QUERY_ATTRIBUTE_PROPERTY   TYPE STRING VALUE 'ALL_QUERY_ATTRIBUTE_PROPERTY',
 ALL_SUBTREE_PROPERTY           TYPE STRING VALUE 'ALL_SUBTREE_PROPERTY',
        END OF PROPERTY,
      END OF ZI_MM_MOV,
    END OF SC_ASSOCIATION_ATTRIBUTE .
  constants:
    SC_BO_KEY  TYPE /BOBF/OBM_BO_KEY VALUE 'A6543B64103C1FE0A88BE93E2C11D8A2' .
  constants:
    SC_BO_NAME TYPE /BOBF/OBM_NAME VALUE 'ZI_MM_MOV' .
  constants:
    BEGIN OF SC_DETERMINATION,
      BEGIN OF ZI_MM_MOV,
 ACTION_AND_FIELD_CONTROL       TYPE /BOBF/DET_KEY VALUE 'A6543B64103C1FE0A88BE93E2C1598A2',
      END OF ZI_MM_MOV,
    END OF SC_DETERMINATION .
  constants:
    BEGIN OF SC_GROUP,
 ZI_MM_MOV                      TYPE /BOBF/OBM_GROUP_KEY VALUE 'A6543B64103C1FE0A88BE94E965678A2',
    END OF SC_GROUP .
  constants:
    SC_MODEL_VERSION TYPE /BOBF/CONF_VERSION VALUE '00000' .
  constants:
    BEGIN OF SC_NODE,
 ZI_MM_MOV                      TYPE /BOBF/OBM_NODE_KEY VALUE 'A6543B64103C1FE0A88BE93E2C1218A2',
 ZI_MM_MOV_LOCK                 TYPE /BOBF/OBM_NODE_KEY VALUE 'A6543B64103C1FE0A88BE93E2C1298A2',
 ZI_MM_MOV_MESSAGE              TYPE /BOBF/OBM_NODE_KEY VALUE 'A6543B64103C1FE0A88BE93E2C1258A2',
 ZI_MM_MOV_PROPERTY             TYPE /BOBF/OBM_NODE_KEY VALUE 'A6543B64103C1FE0A88BE93E2C1358A2',
    END OF SC_NODE .
  constants:
    BEGIN OF SC_NODE_ATTRIBUTE,
      BEGIN OF ZI_MM_MOV,
  NODE_DATA                      TYPE STRING VALUE 'NODE_DATA',
  IDMOV                          TYPE STRING VALUE 'IDMOV',
  MATNR                          TYPE STRING VALUE 'MATNR',
  LOCID                          TYPE STRING VALUE 'LOCID',
  TPMOV                          TYPE STRING VALUE 'TPMOV',
  QTY                            TYPE STRING VALUE 'QTY',
  DATA                           TYPE STRING VALUE 'DATA',
  HORA                           TYPE STRING VALUE 'HORA',
  OBS                            TYPE STRING VALUE 'OBS',
  LOC_DEST                       TYPE STRING VALUE 'LOC_DEST',
      END OF ZI_MM_MOV,
    END OF SC_NODE_ATTRIBUTE .
  constants:
    BEGIN OF SC_NODE_CATEGORY,
      BEGIN OF ZI_MM_MOV,
 ROOT                           TYPE /BOBF/OBM_NODE_CAT_KEY VALUE 'A6543B64103C1FE0A88BE93E2C1238A2',
      END OF ZI_MM_MOV,
    END OF SC_NODE_CATEGORY .
  constants:
    BEGIN OF SC_VALIDATION,
      BEGIN OF ZI_MM_MOV,
 ALTKEY_UNIQUENESS_CHECK        TYPE /BOBF/VAL_KEY VALUE 'A6543B64103C1FE0A88BE93E2C15D8A2',
      END OF ZI_MM_MOV,
    END OF SC_VALIDATION .
endinterface.
