interface ZIF_I_MM_INV_C
  public .


  interfaces /BOBF/IF_LIB_CONSTANTS .

  constants:
    BEGIN OF SC_ACTION,
      BEGIN OF ZI_MM_INV,
 CREATE_ZI_MM_INV               TYPE /BOBF/ACT_KEY VALUE 'A6543B64103C1FE0A88BFA0198E838A2',
 DELETE_ZI_MM_INV               TYPE /BOBF/ACT_KEY VALUE 'A6543B64103C1FE0A88BFA0198E8B8A2',
 LOCK_ZI_MM_INV                 TYPE /BOBF/ACT_KEY VALUE 'A6543B64103C1FE0A88BFA0198E778A2',
 SAVE_ZI_MM_INV                 TYPE /BOBF/ACT_KEY VALUE 'A6543B64103C1FE0A88BFA0198E938A2',
 UNLOCK_ZI_MM_INV               TYPE /BOBF/ACT_KEY VALUE 'A6543B64103C1FE0A88BFA0198E7B8A2',
 UPDATE_ZI_MM_INV               TYPE /BOBF/ACT_KEY VALUE 'A6543B64103C1FE0A88BFA0198E878A2',
 VALIDATE_ZI_MM_INV             TYPE /BOBF/ACT_KEY VALUE 'A6543B64103C1FE0A88BFA0198E8F8A2',
      END OF ZI_MM_INV,
    END OF SC_ACTION .
  constants:
    BEGIN OF SC_ACTION_ATTRIBUTE,
        BEGIN OF ZI_MM_INV,
        BEGIN OF LOCK_ZI_MM_INV,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
 LEGACY_DAC_KEY                 TYPE STRING VALUE 'LEGACY_DAC_KEY',
        END OF LOCK_ZI_MM_INV,
        BEGIN OF UNLOCK_ZI_MM_INV,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
 LEGACY_DAC_KEY                 TYPE STRING VALUE 'LEGACY_DAC_KEY',
        END OF UNLOCK_ZI_MM_INV,
      END OF ZI_MM_INV,
    END OF SC_ACTION_ATTRIBUTE .
  constants:
    BEGIN OF SC_ALTERNATIVE_KEY,
      BEGIN OF ZI_MM_INV,
 DB_KEY                         TYPE /BOBF/OBM_ALTKEY_KEY VALUE 'A6543B64103C1FE0A88BFA0198EA18A2',
      END OF ZI_MM_INV,
    END OF SC_ALTERNATIVE_KEY .
  constants:
    BEGIN OF SC_ASSOCIATION,
      BEGIN OF ZI_MM_INV,
 LOCK                           TYPE /BOBF/OBM_ASSOC_KEY VALUE 'A6543B64103C1FE0A88BFA0198E758A2',
 MESSAGE                        TYPE /BOBF/OBM_ASSOC_KEY VALUE 'A6543B64103C1FE0A88BFA0198E718A2',
 PROPERTY                       TYPE /BOBF/OBM_ASSOC_KEY VALUE 'A6543B64103C1FE0A88BFA0198E818A2',
      END OF ZI_MM_INV,
      BEGIN OF ZI_MM_INV_LOCK,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE 'A6543B64103C1FE0A88BFA0198E998A2',
      END OF ZI_MM_INV_LOCK,
      BEGIN OF ZI_MM_INV_MESSAGE,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE 'A6543B64103C1FE0A88BFA0198E978A2',
      END OF ZI_MM_INV_MESSAGE,
      BEGIN OF ZI_MM_INV_PROPERTY,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE 'A6543B64103C1FE0A88BFA0198E9B8A2',
      END OF ZI_MM_INV_PROPERTY,
    END OF SC_ASSOCIATION .
  constants:
    BEGIN OF SC_ASSOCIATION_ATTRIBUTE,
      BEGIN OF ZI_MM_INV,
        BEGIN OF PROPERTY,
 ALL_NODE_PROPERTY              TYPE STRING VALUE 'ALL_NODE_PROPERTY',
 ALL_NODE_ATTRIBUTE_PROPERTY    TYPE STRING VALUE 'ALL_NODE_ATTRIBUTE_PROPERTY',
 ALL_ASSOCIATION_PROPERTY       TYPE STRING VALUE 'ALL_ASSOCIATION_PROPERTY',
 ALL_ASSOCIATION_ATTRIBUTE_PROP TYPE STRING VALUE 'ALL_ASSOCIATION_ATTRIBUTE_PROP',
 ALL_ACTION_PROPERTY            TYPE STRING VALUE 'ALL_ACTION_PROPERTY',
 ALL_ACTION_ATTRIBUTE_PROPERTY  TYPE STRING VALUE 'ALL_ACTION_ATTRIBUTE_PROPERTY',
 ALL_QUERY_PROPERTY             TYPE STRING VALUE 'ALL_QUERY_PROPERTY',
 ALL_QUERY_ATTRIBUTE_PROPERTY   TYPE STRING VALUE 'ALL_QUERY_ATTRIBUTE_PROPERTY',
 ALL_SUBTREE_PROPERTY           TYPE STRING VALUE 'ALL_SUBTREE_PROPERTY',
        END OF PROPERTY,
      END OF ZI_MM_INV,
    END OF SC_ASSOCIATION_ATTRIBUTE .
  constants:
    SC_BO_KEY  TYPE /BOBF/OBM_BO_KEY VALUE 'A6543B64103C1FE0A88BFA0198E678A2' .
  constants:
    SC_BO_NAME TYPE /BOBF/OBM_NAME VALUE 'ZI_MM_INV' .
  constants:
    BEGIN OF SC_DETERMINATION,
      BEGIN OF ZI_MM_INV,
 ACTION_AND_FIELD_CONTROL       TYPE /BOBF/DET_KEY VALUE 'A6543B64103C1FE0A88BFA0198EA38A2',
      END OF ZI_MM_INV,
    END OF SC_DETERMINATION .
  constants:
    BEGIN OF SC_GROUP,
 ZI_MM_INV                      TYPE /BOBF/OBM_GROUP_KEY VALUE 'A6543B64103C1FE0A88BFA246466D8A2',
    END OF SC_GROUP .
  constants:
    SC_MODEL_VERSION TYPE /BOBF/CONF_VERSION VALUE '00000' .
  constants:
    BEGIN OF SC_NODE,
 ZI_MM_INV                      TYPE /BOBF/OBM_NODE_KEY VALUE 'A6543B64103C1FE0A88BFA0198E6B8A2',
 ZI_MM_INV_LOCK                 TYPE /BOBF/OBM_NODE_KEY VALUE 'A6543B64103C1FE0A88BFA0198E738A2',
 ZI_MM_INV_MESSAGE              TYPE /BOBF/OBM_NODE_KEY VALUE 'A6543B64103C1FE0A88BFA0198E6F8A2',
 ZI_MM_INV_PROPERTY             TYPE /BOBF/OBM_NODE_KEY VALUE 'A6543B64103C1FE0A88BFA0198E7F8A2',
    END OF SC_NODE .
  constants:
    BEGIN OF SC_NODE_ATTRIBUTE,
      BEGIN OF ZI_MM_INV,
  NODE_DATA                      TYPE STRING VALUE 'NODE_DATA',
  IDINV                          TYPE STRING VALUE 'IDINV',
  MATNR                          TYPE STRING VALUE 'MATNR',
  LOCID                          TYPE STRING VALUE 'LOCID',
  QTY_CONTADA                    TYPE STRING VALUE 'QTY_CONTADA',
  DATA_CONT                      TYPE STRING VALUE 'DATA_CONT',
  STATUS                         TYPE STRING VALUE 'STATUS',
      END OF ZI_MM_INV,
    END OF SC_NODE_ATTRIBUTE .
  constants:
    BEGIN OF SC_NODE_CATEGORY,
      BEGIN OF ZI_MM_INV,
 ROOT                           TYPE /BOBF/OBM_NODE_CAT_KEY VALUE 'A6543B64103C1FE0A88BFA0198E6D8A2',
      END OF ZI_MM_INV,
    END OF SC_NODE_CATEGORY .
  constants:
    BEGIN OF SC_VALIDATION,
      BEGIN OF ZI_MM_INV,
 ALTKEY_UNIQUENESS_CHECK        TYPE /BOBF/VAL_KEY VALUE 'A6543B64103C1FE0A88BFA0198EA78A2',
      END OF ZI_MM_INV,
    END OF SC_VALIDATION .
endinterface.
