interface ZIF_I_MM_STOCK_SEARCH_HELP_C
  public .


  interfaces /BOBF/IF_LIB_CONSTANTS .

  constants:
    BEGIN OF SC_ACTION,
      BEGIN OF ZI_MM_STOCK_SEARCH_HELP,
 CREATE_ZI_MM_STOCK_SEARCH_HELP TYPE /BOBF/ACT_KEY VALUE 'A6543B64103C1FE0A89113CBB67538A2',
 DELETE_ZI_MM_STOCK_SEARCH_HELP TYPE /BOBF/ACT_KEY VALUE 'A6543B64103C1FE0A89113CBB675B8A2',
 LOCK_ZI_MM_STOCK_SEARCH_HELP   TYPE /BOBF/ACT_KEY VALUE 'A6543B64103C1FE0A89113CBB67478A2',
 SAVE_ZI_MM_STOCK_SEARCH_HELP   TYPE /BOBF/ACT_KEY VALUE 'A6543B64103C1FE0A89113CBB67638A2',
 UNLOCK_ZI_MM_STOCK_SEARCH_HELP TYPE /BOBF/ACT_KEY VALUE 'A6543B64103C1FE0A89113CBB674B8A2',
 UPDATE_ZI_MM_STOCK_SEARCH_HELP TYPE /BOBF/ACT_KEY VALUE 'A6543B64103C1FE0A89113CBB67578A2',
 VALIDATE_ZI_MM_STOCK_SEARCH_HE TYPE /BOBF/ACT_KEY VALUE 'A6543B64103C1FE0A89113CBB675F8A2',
      END OF ZI_MM_STOCK_SEARCH_HELP,
    END OF SC_ACTION .
  constants:
    BEGIN OF SC_ACTION_ATTRIBUTE,
        BEGIN OF ZI_MM_STOCK_SEARCH_HELP,
        BEGIN OF LOCK_ZI_MM_STOCK_SEARCH_HELP,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
 LEGACY_DAC_KEY                 TYPE STRING VALUE 'LEGACY_DAC_KEY',
        END OF LOCK_ZI_MM_STOCK_SEARCH_HELP,
        BEGIN OF UNLOCK_ZI_MM_STOCK_SEARCH_HELP,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
 LEGACY_DAC_KEY                 TYPE STRING VALUE 'LEGACY_DAC_KEY',
        END OF UNLOCK_ZI_MM_STOCK_SEARCH_HELP,
      END OF ZI_MM_STOCK_SEARCH_HELP,
    END OF SC_ACTION_ATTRIBUTE .
  constants:
    BEGIN OF SC_ALTERNATIVE_KEY,
      BEGIN OF ZI_MM_STOCK_SEARCH_HELP,
 DB_KEY                         TYPE /BOBF/OBM_ALTKEY_KEY VALUE 'A6543B64103C1FE0A89113CBB67718A2',
      END OF ZI_MM_STOCK_SEARCH_HELP,
    END OF SC_ALTERNATIVE_KEY .
  constants:
    BEGIN OF SC_ASSOCIATION,
      BEGIN OF ZI_MM_STOCK_SEARCH_HELP,
 LOCK                           TYPE /BOBF/OBM_ASSOC_KEY VALUE 'A6543B64103C1FE0A89113CBB67458A2',
 MESSAGE                        TYPE /BOBF/OBM_ASSOC_KEY VALUE 'A6543B64103C1FE0A89113CBB67418A2',
 PROPERTY                       TYPE /BOBF/OBM_ASSOC_KEY VALUE 'A6543B64103C1FE0A89113CBB67518A2',
      END OF ZI_MM_STOCK_SEARCH_HELP,
      BEGIN OF ZI_MM_STOCK_SEARCH_HELP_LOCK,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE 'A6543B64103C1FE0A89113CBB67698A2',
      END OF ZI_MM_STOCK_SEARCH_HELP_LOCK,
      BEGIN OF ZI_MM_STOCK_SEARCH_HELP_MESSAG,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE 'A6543B64103C1FE0A89113CBB67678A2',
      END OF ZI_MM_STOCK_SEARCH_HELP_MESSAG,
      BEGIN OF ZI_MM_STOCK_SEARCH_HELP_PROPER,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE 'A6543B64103C1FE0A89113CBB676B8A2',
      END OF ZI_MM_STOCK_SEARCH_HELP_PROPER,
    END OF SC_ASSOCIATION .
  constants:
    BEGIN OF SC_ASSOCIATION_ATTRIBUTE,
      BEGIN OF ZI_MM_STOCK_SEARCH_HELP,
        BEGIN OF PROPERTY,
 ALL_NODE_PROPERTY              TYPE STRING VALUE 'ALL_NODE_PROPERTY',
 ALL_NODE_ATTRIBUTE_PROPERTY    TYPE STRING VALUE 'ALL_NODE_ATTRIBUTE_PROPERTY',
 ALL_ASSOCIATION_PROPERTY       TYPE STRING VALUE 'ALL_ASSOCIATION_PROPERTY',
 ALL_ASSOCIATION_ATTRIBUTE_PROP TYPE STRING VALUE 'ALL_ASSOCIATION_ATTRIBUTE_PROP',
 ALL_ACTION_PROPERTY            TYPE STRING VALUE 'ALL_ACTION_PROPERTY',
 ALL_ACTION_ATTRIBUTE_PROPERTY  TYPE STRING VALUE 'ALL_ACTION_ATTRIBUTE_PROPERTY',
 ALL_QUERY_PROPERTY             TYPE STRING VALUE 'ALL_QUERY_PROPERTY',
 ALL_QUERY_ATTRIBUTE_PROPERTY   TYPE STRING VALUE 'ALL_QUERY_ATTRIBUTE_PROPERTY',
 ALL_SUBTREE_PROPERTY           TYPE STRING VALUE 'ALL_SUBTREE_PROPERTY',
        END OF PROPERTY,
      END OF ZI_MM_STOCK_SEARCH_HELP,
    END OF SC_ASSOCIATION_ATTRIBUTE .
  constants:
    SC_BO_KEY  TYPE /BOBF/OBM_BO_KEY VALUE 'A6543B64103C1FE0A89113CBB67378A2' .
  constants:
    SC_BO_NAME TYPE /BOBF/OBM_NAME VALUE 'ZI_MM_STOCK_SEARCH_HELP' .
  constants:
    BEGIN OF SC_DETERMINATION,
      BEGIN OF ZI_MM_STOCK_SEARCH_HELP,
 ACTION_AND_FIELD_CONTROL       TYPE /BOBF/DET_KEY VALUE 'A6543B64103C1FE0A89113CBB67738A2',
      END OF ZI_MM_STOCK_SEARCH_HELP,
    END OF SC_DETERMINATION .
  constants:
    BEGIN OF SC_GROUP,
 ZI_MM_STOCK_SEARCH_HELP        TYPE /BOBF/OBM_GROUP_KEY VALUE 'A6543B64103C1FE0A89113E4FDB838A2',
    END OF SC_GROUP .
  constants:
    SC_MODEL_VERSION TYPE /BOBF/CONF_VERSION VALUE '00000' .
  constants:
    BEGIN OF SC_NODE,
 ZI_MM_STOCK_SEARCH_HELP        TYPE /BOBF/OBM_NODE_KEY VALUE 'A6543B64103C1FE0A89113CBB673B8A2',
 ZI_MM_STOCK_SEARCH_HELP_LOCK   TYPE /BOBF/OBM_NODE_KEY VALUE 'A6543B64103C1FE0A89113CBB67438A2',
 ZI_MM_STOCK_SEARCH_HELP_MESSAG TYPE /BOBF/OBM_NODE_KEY VALUE 'A6543B64103C1FE0A89113CBB673F8A2',
 ZI_MM_STOCK_SEARCH_HELP_PROPER TYPE /BOBF/OBM_NODE_KEY VALUE 'A6543B64103C1FE0A89113CBB674F8A2',
    END OF SC_NODE .
  constants:
    BEGIN OF SC_NODE_ATTRIBUTE,
      BEGIN OF ZI_MM_STOCK_SEARCH_HELP,
  NODE_DATA                      TYPE STRING VALUE 'NODE_DATA',
  MATNR                          TYPE STRING VALUE 'MATNR',
  LOCID                          TYPE STRING VALUE 'LOCID',
  QTY                            TYPE STRING VALUE 'QTY',
  DT_ATUALIZ                     TYPE STRING VALUE 'DT_ATUALIZ',
      END OF ZI_MM_STOCK_SEARCH_HELP,
    END OF SC_NODE_ATTRIBUTE .
  constants:
    BEGIN OF SC_NODE_CATEGORY,
      BEGIN OF ZI_MM_STOCK_SEARCH_HELP,
 ROOT                           TYPE /BOBF/OBM_NODE_CAT_KEY VALUE 'A6543B64103C1FE0A89113CBB673D8A2',
      END OF ZI_MM_STOCK_SEARCH_HELP,
    END OF SC_NODE_CATEGORY .
  constants:
    BEGIN OF SC_VALIDATION,
      BEGIN OF ZI_MM_STOCK_SEARCH_HELP,
 ALTKEY_UNIQUENESS_CHECK        TYPE /BOBF/VAL_KEY VALUE 'A6543B64103C1FE0A89113CBB67798A2',
      END OF ZI_MM_STOCK_SEARCH_HELP,
    END OF SC_VALIDATION .
endinterface.
