interface ZIF_I_MM_STOCK_C
  public .


  interfaces /BOBF/IF_LIB_CONSTANTS .

  constants:
    BEGIN OF SC_ACTION,
      BEGIN OF ZI_MM_STOCK,
 CREATE_ZI_MM_STOCK             TYPE /BOBF/ACT_KEY VALUE 'A6543B64103C1FE0A88BE0008F8758A2',
 DELETE_ZI_MM_STOCK             TYPE /BOBF/ACT_KEY VALUE 'A6543B64103C1FE0A88BE0008F87D8A2',
 LOCK_ZI_MM_STOCK               TYPE /BOBF/ACT_KEY VALUE 'A6543B64103C1FE0A88BE0008F8698A2',
 SAVE_ZI_MM_STOCK               TYPE /BOBF/ACT_KEY VALUE 'A6543B64103C1FE0A88BE0008F8858A2',
 UNLOCK_ZI_MM_STOCK             TYPE /BOBF/ACT_KEY VALUE 'A6543B64103C1FE0A88BE0008F86D8A2',
 UPDATE_ZI_MM_STOCK             TYPE /BOBF/ACT_KEY VALUE 'A6543B64103C1FE0A88BE0008F8798A2',
 VALIDATE_ZI_MM_STOCK           TYPE /BOBF/ACT_KEY VALUE 'A6543B64103C1FE0A88BE0008F8818A2',
      END OF ZI_MM_STOCK,
    END OF SC_ACTION .
  constants:
    BEGIN OF SC_ACTION_ATTRIBUTE,
        BEGIN OF ZI_MM_STOCK,
        BEGIN OF LOCK_ZI_MM_STOCK,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
 LEGACY_DAC_KEY                 TYPE STRING VALUE 'LEGACY_DAC_KEY',
        END OF LOCK_ZI_MM_STOCK,
        BEGIN OF UNLOCK_ZI_MM_STOCK,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
 LEGACY_DAC_KEY                 TYPE STRING VALUE 'LEGACY_DAC_KEY',
        END OF UNLOCK_ZI_MM_STOCK,
      END OF ZI_MM_STOCK,
    END OF SC_ACTION_ATTRIBUTE .
  constants:
    BEGIN OF SC_ALTERNATIVE_KEY,
      BEGIN OF ZI_MM_STOCK,
 DB_KEY                         TYPE /BOBF/OBM_ALTKEY_KEY VALUE 'A6543B64103C1FE0A88BE0008F8938A2',
      END OF ZI_MM_STOCK,
    END OF SC_ALTERNATIVE_KEY .
  constants:
    BEGIN OF SC_ASSOCIATION,
      BEGIN OF ZI_MM_STOCK,
 LOCK                           TYPE /BOBF/OBM_ASSOC_KEY VALUE 'A6543B64103C1FE0A88BE0008F8678A2',
 MESSAGE                        TYPE /BOBF/OBM_ASSOC_KEY VALUE 'A6543B64103C1FE0A88BE0008F8638A2',
 PROPERTY                       TYPE /BOBF/OBM_ASSOC_KEY VALUE 'A6543B64103C1FE0A88BE0008F8738A2',
      END OF ZI_MM_STOCK,
      BEGIN OF ZI_MM_STOCK_LOCK,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE 'A6543B64103C1FE0A88BE0008F88B8A2',
      END OF ZI_MM_STOCK_LOCK,
      BEGIN OF ZI_MM_STOCK_MESSAGE,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE 'A6543B64103C1FE0A88BE0008F8898A2',
      END OF ZI_MM_STOCK_MESSAGE,
      BEGIN OF ZI_MM_STOCK_PROPERTY,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE 'A6543B64103C1FE0A88BE0008F88D8A2',
      END OF ZI_MM_STOCK_PROPERTY,
    END OF SC_ASSOCIATION .
  constants:
    BEGIN OF SC_ASSOCIATION_ATTRIBUTE,
      BEGIN OF ZI_MM_STOCK,
        BEGIN OF PROPERTY,
 ALL_NODE_PROPERTY              TYPE STRING VALUE 'ALL_NODE_PROPERTY',
 ALL_NODE_ATTRIBUTE_PROPERTY    TYPE STRING VALUE 'ALL_NODE_ATTRIBUTE_PROPERTY',
 ALL_ASSOCIATION_PROPERTY       TYPE STRING VALUE 'ALL_ASSOCIATION_PROPERTY',
 ALL_ASSOCIATION_ATTRIBUTE_PROP TYPE STRING VALUE 'ALL_ASSOCIATION_ATTRIBUTE_PROP',
 ALL_ACTION_PROPERTY            TYPE STRING VALUE 'ALL_ACTION_PROPERTY',
 ALL_ACTION_ATTRIBUTE_PROPERTY  TYPE STRING VALUE 'ALL_ACTION_ATTRIBUTE_PROPERTY',
 ALL_QUERY_PROPERTY             TYPE STRING VALUE 'ALL_QUERY_PROPERTY',
 ALL_QUERY_ATTRIBUTE_PROPERTY   TYPE STRING VALUE 'ALL_QUERY_ATTRIBUTE_PROPERTY',
 ALL_SUBTREE_PROPERTY           TYPE STRING VALUE 'ALL_SUBTREE_PROPERTY',
        END OF PROPERTY,
      END OF ZI_MM_STOCK,
    END OF SC_ASSOCIATION_ATTRIBUTE .
  constants:
    SC_BO_KEY  TYPE /BOBF/OBM_BO_KEY VALUE 'A6543B64103C1FE0A88BE0008F8598A2' .
  constants:
    SC_BO_NAME TYPE /BOBF/OBM_NAME VALUE 'ZI_MM_STOCK' .
  constants:
    BEGIN OF SC_DETERMINATION,
      BEGIN OF ZI_MM_STOCK,
 ACTION_AND_FIELD_CONTROL       TYPE /BOBF/DET_KEY VALUE 'A6543B64103C1FE0A88BE0008F8958A2',
      END OF ZI_MM_STOCK,
    END OF SC_DETERMINATION .
  constants:
    BEGIN OF SC_GROUP,
 ZI_MM_STOCK                    TYPE /BOBF/OBM_GROUP_KEY VALUE 'A6543B64103C1FE0A88BE010C1EEF8A2',
    END OF SC_GROUP .
  constants:
    SC_MODEL_VERSION TYPE /BOBF/CONF_VERSION VALUE '00000' .
  constants:
    BEGIN OF SC_NODE,
 ZI_MM_STOCK                    TYPE /BOBF/OBM_NODE_KEY VALUE 'A6543B64103C1FE0A88BE0008F85D8A2',
 ZI_MM_STOCK_LOCK               TYPE /BOBF/OBM_NODE_KEY VALUE 'A6543B64103C1FE0A88BE0008F8658A2',
 ZI_MM_STOCK_MESSAGE            TYPE /BOBF/OBM_NODE_KEY VALUE 'A6543B64103C1FE0A88BE0008F8618A2',
 ZI_MM_STOCK_PROPERTY           TYPE /BOBF/OBM_NODE_KEY VALUE 'A6543B64103C1FE0A88BE0008F8718A2',
    END OF SC_NODE .
  constants:
    BEGIN OF SC_NODE_ATTRIBUTE,
      BEGIN OF ZI_MM_STOCK,
  NODE_DATA                      TYPE STRING VALUE 'NODE_DATA',
  MATNR                          TYPE STRING VALUE 'MATNR',
  LOCID                          TYPE STRING VALUE 'LOCID',
  QTY                            TYPE STRING VALUE 'QTY',
  DT_ATUALIZ                     TYPE STRING VALUE 'DT_ATUALIZ',
      END OF ZI_MM_STOCK,
    END OF SC_NODE_ATTRIBUTE .
  constants:
    BEGIN OF SC_NODE_CATEGORY,
      BEGIN OF ZI_MM_STOCK,
 ROOT                           TYPE /BOBF/OBM_NODE_CAT_KEY VALUE 'A6543B64103C1FE0A88BE0008F85F8A2',
      END OF ZI_MM_STOCK,
    END OF SC_NODE_CATEGORY .
  constants:
    BEGIN OF SC_VALIDATION,
      BEGIN OF ZI_MM_STOCK,
 ALTKEY_UNIQUENESS_CHECK        TYPE /BOBF/VAL_KEY VALUE 'A6543B64103C1FE0A88BE0008F89B8A2',
      END OF ZI_MM_STOCK,
    END OF SC_VALIDATION .
endinterface.
