interface ZIF_I_MM_STOCK_NAV_C
  public .


  interfaces /BOBF/IF_LIB_CONSTANTS .

  constants:
    BEGIN OF SC_ACTION,
      BEGIN OF ZI_MM_STOCK_NAV,
 CREATE_ZI_MM_STOCK_NAV         TYPE /BOBF/ACT_KEY VALUE 'A6543B64103C1FE0A88C19778BE238A2',
 DELETE_ZI_MM_STOCK_NAV         TYPE /BOBF/ACT_KEY VALUE 'A6543B64103C1FE0A88C19778BE2B8A2',
 LOCK_ZI_MM_STOCK_NAV           TYPE /BOBF/ACT_KEY VALUE 'A6543B64103C1FE0A88C19778BE178A2',
 SAVE_ZI_MM_STOCK_NAV           TYPE /BOBF/ACT_KEY VALUE 'A6543B64103C1FE0A88C19778BE338A2',
 UNLOCK_ZI_MM_STOCK_NAV         TYPE /BOBF/ACT_KEY VALUE 'A6543B64103C1FE0A88C19778BE1B8A2',
 UPDATE_ZI_MM_STOCK_NAV         TYPE /BOBF/ACT_KEY VALUE 'A6543B64103C1FE0A88C19778BE278A2',
 VALIDATE_ZI_MM_STOCK_NAV       TYPE /BOBF/ACT_KEY VALUE 'A6543B64103C1FE0A88C19778BE2F8A2',
      END OF ZI_MM_STOCK_NAV,
    END OF SC_ACTION .
  constants:
    BEGIN OF SC_ACTION_ATTRIBUTE,
        BEGIN OF ZI_MM_STOCK_NAV,
        BEGIN OF LOCK_ZI_MM_STOCK_NAV,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
 LEGACY_DAC_KEY                 TYPE STRING VALUE 'LEGACY_DAC_KEY',
        END OF LOCK_ZI_MM_STOCK_NAV,
        BEGIN OF UNLOCK_ZI_MM_STOCK_NAV,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
 LEGACY_DAC_KEY                 TYPE STRING VALUE 'LEGACY_DAC_KEY',
        END OF UNLOCK_ZI_MM_STOCK_NAV,
      END OF ZI_MM_STOCK_NAV,
    END OF SC_ACTION_ATTRIBUTE .
  constants:
    BEGIN OF SC_ALTERNATIVE_KEY,
      BEGIN OF ZI_MM_STOCK_NAV,
 DB_KEY                         TYPE /BOBF/OBM_ALTKEY_KEY VALUE 'A6543B64103C1FE0A88C19778BE418A2',
      END OF ZI_MM_STOCK_NAV,
    END OF SC_ALTERNATIVE_KEY .
  constants:
    BEGIN OF SC_ASSOCIATION,
      BEGIN OF ZI_MM_STOCK_NAV,
 LOCK                           TYPE /BOBF/OBM_ASSOC_KEY VALUE 'A6543B64103C1FE0A88C19778BE158A2',
 MESSAGE                        TYPE /BOBF/OBM_ASSOC_KEY VALUE 'A6543B64103C1FE0A88C19778BE118A2',
 PROPERTY                       TYPE /BOBF/OBM_ASSOC_KEY VALUE 'A6543B64103C1FE0A88C19778BE218A2',
      END OF ZI_MM_STOCK_NAV,
      BEGIN OF ZI_MM_STOCK_NAV_LOCK,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE 'A6543B64103C1FE0A88C19778BE398A2',
      END OF ZI_MM_STOCK_NAV_LOCK,
      BEGIN OF ZI_MM_STOCK_NAV_MESSAGE,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE 'A6543B64103C1FE0A88C19778BE378A2',
      END OF ZI_MM_STOCK_NAV_MESSAGE,
      BEGIN OF ZI_MM_STOCK_NAV_PROPERTY,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE 'A6543B64103C1FE0A88C19778BE3B8A2',
      END OF ZI_MM_STOCK_NAV_PROPERTY,
    END OF SC_ASSOCIATION .
  constants:
    BEGIN OF SC_ASSOCIATION_ATTRIBUTE,
      BEGIN OF ZI_MM_STOCK_NAV,
        BEGIN OF PROPERTY,
 ALL_NODE_PROPERTY              TYPE STRING VALUE 'ALL_NODE_PROPERTY',
 ALL_NODE_ATTRIBUTE_PROPERTY    TYPE STRING VALUE 'ALL_NODE_ATTRIBUTE_PROPERTY',
 ALL_ASSOCIATION_PROPERTY       TYPE STRING VALUE 'ALL_ASSOCIATION_PROPERTY',
 ALL_ASSOCIATION_ATTRIBUTE_PROP TYPE STRING VALUE 'ALL_ASSOCIATION_ATTRIBUTE_PROP',
 ALL_ACTION_PROPERTY            TYPE STRING VALUE 'ALL_ACTION_PROPERTY',
 ALL_ACTION_ATTRIBUTE_PROPERTY  TYPE STRING VALUE 'ALL_ACTION_ATTRIBUTE_PROPERTY',
 ALL_QUERY_PROPERTY             TYPE STRING VALUE 'ALL_QUERY_PROPERTY',
 ALL_QUERY_ATTRIBUTE_PROPERTY   TYPE STRING VALUE 'ALL_QUERY_ATTRIBUTE_PROPERTY',
 ALL_SUBTREE_PROPERTY           TYPE STRING VALUE 'ALL_SUBTREE_PROPERTY',
        END OF PROPERTY,
      END OF ZI_MM_STOCK_NAV,
    END OF SC_ASSOCIATION_ATTRIBUTE .
  constants:
    SC_BO_KEY  TYPE /BOBF/OBM_BO_KEY VALUE 'A6543B64103C1FE0A88C19778BE078A2' .
  constants:
    SC_BO_NAME TYPE /BOBF/OBM_NAME VALUE 'ZI_MM_STOCK_NAV' .
  constants:
    BEGIN OF SC_DETERMINATION,
      BEGIN OF ZI_MM_STOCK_NAV,
 ACTION_AND_FIELD_CONTROL       TYPE /BOBF/DET_KEY VALUE 'A6543B64103C1FE0A88C19778BE438A2',
      END OF ZI_MM_STOCK_NAV,
    END OF SC_DETERMINATION .
  constants:
    BEGIN OF SC_GROUP,
 ZI_MM_STOCK_NAV                TYPE /BOBF/OBM_GROUP_KEY VALUE 'A6543B64103C1FE0A88C1994A85EF8A2',
    END OF SC_GROUP .
  constants:
    SC_MODEL_VERSION TYPE /BOBF/CONF_VERSION VALUE '00000' .
  constants:
    BEGIN OF SC_NODE,
 ZI_MM_STOCK_NAV                TYPE /BOBF/OBM_NODE_KEY VALUE 'A6543B64103C1FE0A88C19778BE0B8A2',
 ZI_MM_STOCK_NAV_LOCK           TYPE /BOBF/OBM_NODE_KEY VALUE 'A6543B64103C1FE0A88C19778BE138A2',
 ZI_MM_STOCK_NAV_MESSAGE        TYPE /BOBF/OBM_NODE_KEY VALUE 'A6543B64103C1FE0A88C19778BE0F8A2',
 ZI_MM_STOCK_NAV_PROPERTY       TYPE /BOBF/OBM_NODE_KEY VALUE 'A6543B64103C1FE0A88C19778BE1F8A2',
    END OF SC_NODE .
  constants:
    BEGIN OF SC_NODE_ATTRIBUTE,
      BEGIN OF ZI_MM_STOCK_NAV,
  NODE_DATA                      TYPE STRING VALUE 'NODE_DATA',
  MATNR                          TYPE STRING VALUE 'MATNR',
  LOCID                          TYPE STRING VALUE 'LOCID',
  QTY                            TYPE STRING VALUE 'QTY',
  DT_ATUALIZ                     TYPE STRING VALUE 'DT_ATUALIZ',
      END OF ZI_MM_STOCK_NAV,
    END OF SC_NODE_ATTRIBUTE .
  constants:
    BEGIN OF SC_NODE_CATEGORY,
      BEGIN OF ZI_MM_STOCK_NAV,
 ROOT                           TYPE /BOBF/OBM_NODE_CAT_KEY VALUE 'A6543B64103C1FE0A88C19778BE0D8A2',
      END OF ZI_MM_STOCK_NAV,
    END OF SC_NODE_CATEGORY .
  constants:
    BEGIN OF SC_VALIDATION,
      BEGIN OF ZI_MM_STOCK_NAV,
 ALTKEY_UNIQUENESS_CHECK        TYPE /BOBF/VAL_KEY VALUE 'A6543B64103C1FE0A88C19778BE498A2',
      END OF ZI_MM_STOCK_NAV,
    END OF SC_VALIDATION .
endinterface.
