interface ZIF_I_MM_LOC_C
  public .


  interfaces /BOBF/IF_LIB_CONSTANTS .

  constants:
    BEGIN OF SC_ACTION,
      BEGIN OF ZI_MM_LOC,
 CREATE_ZI_MM_LOC               TYPE /BOBF/ACT_KEY VALUE 'A6543B64103C1FE0A88BCD7690C7B8A2',
 DELETE_ZI_MM_LOC               TYPE /BOBF/ACT_KEY VALUE 'A6543B64103C1FE0A88BCD7690C838A2',
 LOCK_ZI_MM_LOC                 TYPE /BOBF/ACT_KEY VALUE 'A6543B64103C1FE0A88BCD7690C6F8A2',
 SAVE_ZI_MM_LOC                 TYPE /BOBF/ACT_KEY VALUE 'A6543B64103C1FE0A88BCD7690C8B8A2',
 UNLOCK_ZI_MM_LOC               TYPE /BOBF/ACT_KEY VALUE 'A6543B64103C1FE0A88BCD7690C738A2',
 UPDATE_ZI_MM_LOC               TYPE /BOBF/ACT_KEY VALUE 'A6543B64103C1FE0A88BCD7690C7F8A2',
 VALIDATE_ZI_MM_LOC             TYPE /BOBF/ACT_KEY VALUE 'A6543B64103C1FE0A88BCD7690C878A2',
      END OF ZI_MM_LOC,
    END OF SC_ACTION .
  constants:
    BEGIN OF SC_ACTION_ATTRIBUTE,
        BEGIN OF ZI_MM_LOC,
        BEGIN OF LOCK_ZI_MM_LOC,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
 LEGACY_DAC_KEY                 TYPE STRING VALUE 'LEGACY_DAC_KEY',
        END OF LOCK_ZI_MM_LOC,
        BEGIN OF UNLOCK_ZI_MM_LOC,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
 LEGACY_DAC_KEY                 TYPE STRING VALUE 'LEGACY_DAC_KEY',
        END OF UNLOCK_ZI_MM_LOC,
      END OF ZI_MM_LOC,
    END OF SC_ACTION_ATTRIBUTE .
  constants:
    BEGIN OF SC_ALTERNATIVE_KEY,
      BEGIN OF ZI_MM_LOC,
 DB_KEY                         TYPE /BOBF/OBM_ALTKEY_KEY VALUE 'A6543B64103C1FE0A88BCD7690C998A2',
      END OF ZI_MM_LOC,
    END OF SC_ALTERNATIVE_KEY .
  constants:
    BEGIN OF SC_ASSOCIATION,
      BEGIN OF ZI_MM_LOC,
 LOCK                           TYPE /BOBF/OBM_ASSOC_KEY VALUE 'A6543B64103C1FE0A88BCD7690C6D8A2',
 MESSAGE                        TYPE /BOBF/OBM_ASSOC_KEY VALUE 'A6543B64103C1FE0A88BCD7690C698A2',
 PROPERTY                       TYPE /BOBF/OBM_ASSOC_KEY VALUE 'A6543B64103C1FE0A88BCD7690C798A2',
      END OF ZI_MM_LOC,
      BEGIN OF ZI_MM_LOC_LOCK,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE 'A6543B64103C1FE0A88BCD7690C918A2',
      END OF ZI_MM_LOC_LOCK,
      BEGIN OF ZI_MM_LOC_MESSAGE,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE 'A6543B64103C1FE0A88BCD7690C8F8A2',
      END OF ZI_MM_LOC_MESSAGE,
      BEGIN OF ZI_MM_LOC_PROPERTY,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE 'A6543B64103C1FE0A88BCD7690C938A2',
      END OF ZI_MM_LOC_PROPERTY,
    END OF SC_ASSOCIATION .
  constants:
    BEGIN OF SC_ASSOCIATION_ATTRIBUTE,
      BEGIN OF ZI_MM_LOC,
        BEGIN OF PROPERTY,
 ALL_NODE_PROPERTY              TYPE STRING VALUE 'ALL_NODE_PROPERTY',
 ALL_NODE_ATTRIBUTE_PROPERTY    TYPE STRING VALUE 'ALL_NODE_ATTRIBUTE_PROPERTY',
 ALL_ASSOCIATION_PROPERTY       TYPE STRING VALUE 'ALL_ASSOCIATION_PROPERTY',
 ALL_ASSOCIATION_ATTRIBUTE_PROP TYPE STRING VALUE 'ALL_ASSOCIATION_ATTRIBUTE_PROP',
 ALL_ACTION_PROPERTY            TYPE STRING VALUE 'ALL_ACTION_PROPERTY',
 ALL_ACTION_ATTRIBUTE_PROPERTY  TYPE STRING VALUE 'ALL_ACTION_ATTRIBUTE_PROPERTY',
 ALL_QUERY_PROPERTY             TYPE STRING VALUE 'ALL_QUERY_PROPERTY',
 ALL_QUERY_ATTRIBUTE_PROPERTY   TYPE STRING VALUE 'ALL_QUERY_ATTRIBUTE_PROPERTY',
 ALL_SUBTREE_PROPERTY           TYPE STRING VALUE 'ALL_SUBTREE_PROPERTY',
        END OF PROPERTY,
      END OF ZI_MM_LOC,
    END OF SC_ASSOCIATION_ATTRIBUTE .
  constants:
    SC_BO_KEY  TYPE /BOBF/OBM_BO_KEY VALUE 'A6543B64103C1FE0A88BCD7690C5F8A2' .
  constants:
    SC_BO_NAME TYPE /BOBF/OBM_NAME VALUE 'ZI_MM_LOC' .
  constants:
    BEGIN OF SC_DETERMINATION,
      BEGIN OF ZI_MM_LOC,
 ACTION_AND_FIELD_CONTROL       TYPE /BOBF/DET_KEY VALUE 'A6543B64103C1FE0A88BCD7690C9B8A2',
      END OF ZI_MM_LOC,
    END OF SC_DETERMINATION .
  constants:
    BEGIN OF SC_GROUP,
 ZI_MM_LOC                      TYPE /BOBF/OBM_GROUP_KEY VALUE 'A6543B64103C1FE0A88BCD7690CD38A2',
    END OF SC_GROUP .
  constants:
    SC_MODEL_VERSION TYPE /BOBF/CONF_VERSION VALUE '00000' .
  constants:
    BEGIN OF SC_NODE,
 ZI_MM_LOC                      TYPE /BOBF/OBM_NODE_KEY VALUE 'A6543B64103C1FE0A88BCD7690C638A2',
 ZI_MM_LOC_LOCK                 TYPE /BOBF/OBM_NODE_KEY VALUE 'A6543B64103C1FE0A88BCD7690C6B8A2',
 ZI_MM_LOC_MESSAGE              TYPE /BOBF/OBM_NODE_KEY VALUE 'A6543B64103C1FE0A88BCD7690C678A2',
 ZI_MM_LOC_PROPERTY             TYPE /BOBF/OBM_NODE_KEY VALUE 'A6543B64103C1FE0A88BCD7690C778A2',
    END OF SC_NODE .
  constants:
    BEGIN OF SC_NODE_ATTRIBUTE,
      BEGIN OF ZI_MM_LOC,
  NODE_DATA                      TYPE STRING VALUE 'NODE_DATA',
  LOCID                          TYPE STRING VALUE 'LOCID',
  DESCR                          TYPE STRING VALUE 'DESCR',
  ATIVO                          TYPE STRING VALUE 'ATIVO',
      END OF ZI_MM_LOC,
    END OF SC_NODE_ATTRIBUTE .
  constants:
    BEGIN OF SC_NODE_CATEGORY,
      BEGIN OF ZI_MM_LOC,
 ROOT                           TYPE /BOBF/OBM_NODE_CAT_KEY VALUE 'A6543B64103C1FE0A88BCD7690C658A2',
      END OF ZI_MM_LOC,
    END OF SC_NODE_CATEGORY .
  constants:
    BEGIN OF SC_VALIDATION,
      BEGIN OF ZI_MM_LOC,
 ALTKEY_UNIQUENESS_CHECK        TYPE /BOBF/VAL_KEY VALUE 'A6543B64103C1FE0A88BCD7690C9F8A2',
      END OF ZI_MM_LOC,
    END OF SC_VALIDATION .
endinterface.
