interface ZIF_I_SD_CUST_NEW_C
  public .


  interfaces /BOBF/IF_LIB_CONSTANTS .

  constants:
    BEGIN OF SC_ACTION,
      BEGIN OF ZI_SD_CUST_NEW,
 CREATE_ZI_SD_CUST_NEW          TYPE /BOBF/ACT_KEY VALUE 'A6543B64103C1FE0A7E1B8472F3C38A2',
 DELETE_ZI_SD_CUST_NEW          TYPE /BOBF/ACT_KEY VALUE 'A6543B64103C1FE0A7E1B8472F3CB8A2',
 LOCK_ZI_SD_CUST_NEW            TYPE /BOBF/ACT_KEY VALUE 'A6543B64103C1FE0A7E1B8472F3B78A2',
 SAVE_ZI_SD_CUST_NEW            TYPE /BOBF/ACT_KEY VALUE 'A6543B64103C1FE0A7E1B8472F3D38A2',
 UNLOCK_ZI_SD_CUST_NEW          TYPE /BOBF/ACT_KEY VALUE 'A6543B64103C1FE0A7E1B8472F3BB8A2',
 UPDATE_ZI_SD_CUST_NEW          TYPE /BOBF/ACT_KEY VALUE 'A6543B64103C1FE0A7E1B8472F3C78A2',
 VALIDATE_ZI_SD_CUST_NEW        TYPE /BOBF/ACT_KEY VALUE 'A6543B64103C1FE0A7E1B8472F3CF8A2',
      END OF ZI_SD_CUST_NEW,
    END OF SC_ACTION .
  constants:
    BEGIN OF SC_ACTION_ATTRIBUTE,
        BEGIN OF ZI_SD_CUST_NEW,
        BEGIN OF LOCK_ZI_SD_CUST_NEW,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
 LEGACY_DAC_KEY                 TYPE STRING VALUE 'LEGACY_DAC_KEY',
        END OF LOCK_ZI_SD_CUST_NEW,
        BEGIN OF UNLOCK_ZI_SD_CUST_NEW,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
 LEGACY_DAC_KEY                 TYPE STRING VALUE 'LEGACY_DAC_KEY',
        END OF UNLOCK_ZI_SD_CUST_NEW,
      END OF ZI_SD_CUST_NEW,
    END OF SC_ACTION_ATTRIBUTE .
  constants:
    BEGIN OF SC_ALTERNATIVE_KEY,
      BEGIN OF ZI_SD_CUST_NEW,
 DB_KEY                         TYPE /BOBF/OBM_ALTKEY_KEY VALUE 'A6543B64103C1FE0A7E1B8472F3E18A2',
      END OF ZI_SD_CUST_NEW,
    END OF SC_ALTERNATIVE_KEY .
  constants:
    BEGIN OF SC_ASSOCIATION,
      BEGIN OF ZI_SD_CUST_NEW,
 LOCK                           TYPE /BOBF/OBM_ASSOC_KEY VALUE 'A6543B64103C1FE0A7E1B8472F3B58A2',
 MESSAGE                        TYPE /BOBF/OBM_ASSOC_KEY VALUE 'A6543B64103C1FE0A7E1B8472F3B18A2',
 PROPERTY                       TYPE /BOBF/OBM_ASSOC_KEY VALUE 'A6543B64103C1FE0A7E1B8472F3C18A2',
      END OF ZI_SD_CUST_NEW,
      BEGIN OF ZI_SD_CUST_NEW_LOCK,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE 'A6543B64103C1FE0A7E1B8472F3D98A2',
      END OF ZI_SD_CUST_NEW_LOCK,
      BEGIN OF ZI_SD_CUST_NEW_MESSAGE,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE 'A6543B64103C1FE0A7E1B8472F3D78A2',
      END OF ZI_SD_CUST_NEW_MESSAGE,
      BEGIN OF ZI_SD_CUST_NEW_PROPERTY,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE 'A6543B64103C1FE0A7E1B8472F3DB8A2',
      END OF ZI_SD_CUST_NEW_PROPERTY,
    END OF SC_ASSOCIATION .
  constants:
    BEGIN OF SC_ASSOCIATION_ATTRIBUTE,
      BEGIN OF ZI_SD_CUST_NEW,
        BEGIN OF PROPERTY,
 ALL_NODE_PROPERTY              TYPE STRING VALUE 'ALL_NODE_PROPERTY',
 ALL_NODE_ATTRIBUTE_PROPERTY    TYPE STRING VALUE 'ALL_NODE_ATTRIBUTE_PROPERTY',
 ALL_ASSOCIATION_PROPERTY       TYPE STRING VALUE 'ALL_ASSOCIATION_PROPERTY',
 ALL_ASSOCIATION_ATTRIBUTE_PROP TYPE STRING VALUE 'ALL_ASSOCIATION_ATTRIBUTE_PROP',
 ALL_ACTION_PROPERTY            TYPE STRING VALUE 'ALL_ACTION_PROPERTY',
 ALL_ACTION_ATTRIBUTE_PROPERTY  TYPE STRING VALUE 'ALL_ACTION_ATTRIBUTE_PROPERTY',
 ALL_QUERY_PROPERTY             TYPE STRING VALUE 'ALL_QUERY_PROPERTY',
 ALL_QUERY_ATTRIBUTE_PROPERTY   TYPE STRING VALUE 'ALL_QUERY_ATTRIBUTE_PROPERTY',
 ALL_SUBTREE_PROPERTY           TYPE STRING VALUE 'ALL_SUBTREE_PROPERTY',
        END OF PROPERTY,
      END OF ZI_SD_CUST_NEW,
    END OF SC_ASSOCIATION_ATTRIBUTE .
  constants:
    SC_BO_KEY  TYPE /BOBF/OBM_BO_KEY VALUE 'A6543B64103C1FE0A7E1B8472F3A78A2' .
  constants:
    SC_BO_NAME TYPE /BOBF/OBM_NAME VALUE 'ZI_SD_CUST_NEW' .
  constants:
    BEGIN OF SC_DETERMINATION,
      BEGIN OF ZI_SD_CUST_NEW,
 ACTION_AND_FIELD_CONTROL       TYPE /BOBF/DET_KEY VALUE 'A6543B64103C1FE0A7E1B8472F3E38A2',
      END OF ZI_SD_CUST_NEW,
    END OF SC_DETERMINATION .
  constants:
    BEGIN OF SC_GROUP,
 ZI_SD_CUST_NEW                 TYPE /BOBF/OBM_GROUP_KEY VALUE 'A6543B64103C1FE0A7E1B8472F4238A2',
    END OF SC_GROUP .
  constants:
    SC_MODEL_VERSION TYPE /BOBF/CONF_VERSION VALUE '00000' .
  constants:
    BEGIN OF SC_NODE,
 ZI_SD_CUST_NEW                 TYPE /BOBF/OBM_NODE_KEY VALUE 'A6543B64103C1FE0A7E1B8472F3AB8A2',
 ZI_SD_CUST_NEW_LOCK            TYPE /BOBF/OBM_NODE_KEY VALUE 'A6543B64103C1FE0A7E1B8472F3B38A2',
 ZI_SD_CUST_NEW_MESSAGE         TYPE /BOBF/OBM_NODE_KEY VALUE 'A6543B64103C1FE0A7E1B8472F3AF8A2',
 ZI_SD_CUST_NEW_PROPERTY        TYPE /BOBF/OBM_NODE_KEY VALUE 'A6543B64103C1FE0A7E1B8472F3BF8A2',
    END OF SC_NODE .
  constants:
    BEGIN OF SC_NODE_ATTRIBUTE,
      BEGIN OF ZI_SD_CUST_NEW,
  NODE_DATA                      TYPE STRING VALUE 'NODE_DATA',
  CUSTID                         TYPE STRING VALUE 'CUSTID',
  CPF                            TYPE STRING VALUE 'CPF',
  NOME                           TYPE STRING VALUE 'NOME',
  ATIVO                          TYPE STRING VALUE 'ATIVO',
      END OF ZI_SD_CUST_NEW,
    END OF SC_NODE_ATTRIBUTE .
  constants:
    BEGIN OF SC_NODE_CATEGORY,
      BEGIN OF ZI_SD_CUST_NEW,
 ROOT                           TYPE /BOBF/OBM_NODE_CAT_KEY VALUE 'A6543B64103C1FE0A7E1B8472F3AD8A2',
      END OF ZI_SD_CUST_NEW,
    END OF SC_NODE_CATEGORY .
  constants:
    BEGIN OF SC_VALIDATION,
      BEGIN OF ZI_SD_CUST_NEW,
 ALTKEY_UNIQUENESS_CHECK        TYPE /BOBF/VAL_KEY VALUE 'A6543B64103C1FE0A7E1B8472F3E98A2',
      END OF ZI_SD_CUST_NEW,
    END OF SC_VALIDATION .
endinterface.
