interface ZIF_I_SD_ITEMS_NEW_C
  public .


  interfaces /BOBF/IF_LIB_CONSTANTS .

  constants:
    BEGIN OF SC_ACTION,
      BEGIN OF ZI_SD_ITEMS_NEW,
 CREATE_ZI_SD_ITEMS_NEW         TYPE /BOBF/ACT_KEY VALUE 'A6543B64103C1FE0A7E1B5732BB738A2',
 DELETE_ZI_SD_ITEMS_NEW         TYPE /BOBF/ACT_KEY VALUE 'A6543B64103C1FE0A7E1B5732BB7B8A2',
 LOCK_ZI_SD_ITEMS_NEW           TYPE /BOBF/ACT_KEY VALUE 'A6543B64103C1FE0A7E1B5732BB678A2',
 SAVE_ZI_SD_ITEMS_NEW           TYPE /BOBF/ACT_KEY VALUE 'A6543B64103C1FE0A7E1B5732BB838A2',
 UNLOCK_ZI_SD_ITEMS_NEW         TYPE /BOBF/ACT_KEY VALUE 'A6543B64103C1FE0A7E1B5732BB6B8A2',
 UPDATE_ZI_SD_ITEMS_NEW         TYPE /BOBF/ACT_KEY VALUE 'A6543B64103C1FE0A7E1B5732BB778A2',
 VALIDATE_ZI_SD_ITEMS_NEW       TYPE /BOBF/ACT_KEY VALUE 'A6543B64103C1FE0A7E1B5732BB7F8A2',
      END OF ZI_SD_ITEMS_NEW,
    END OF SC_ACTION .
  constants:
    BEGIN OF SC_ACTION_ATTRIBUTE,
        BEGIN OF ZI_SD_ITEMS_NEW,
        BEGIN OF LOCK_ZI_SD_ITEMS_NEW,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
 LEGACY_DAC_KEY                 TYPE STRING VALUE 'LEGACY_DAC_KEY',
        END OF LOCK_ZI_SD_ITEMS_NEW,
        BEGIN OF UNLOCK_ZI_SD_ITEMS_NEW,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
 LEGACY_DAC_KEY                 TYPE STRING VALUE 'LEGACY_DAC_KEY',
        END OF UNLOCK_ZI_SD_ITEMS_NEW,
      END OF ZI_SD_ITEMS_NEW,
    END OF SC_ACTION_ATTRIBUTE .
  constants:
    BEGIN OF SC_ALTERNATIVE_KEY,
      BEGIN OF ZI_SD_ITEMS_NEW,
 DB_KEY                         TYPE /BOBF/OBM_ALTKEY_KEY VALUE 'A6543B64103C1FE0A7E1B5732BB918A2',
      END OF ZI_SD_ITEMS_NEW,
    END OF SC_ALTERNATIVE_KEY .
  constants:
    BEGIN OF SC_ASSOCIATION,
      BEGIN OF ZI_SD_ITEMS_NEW,
 LOCK                           TYPE /BOBF/OBM_ASSOC_KEY VALUE 'A6543B64103C1FE0A7E1B5732BB658A2',
 MESSAGE                        TYPE /BOBF/OBM_ASSOC_KEY VALUE 'A6543B64103C1FE0A7E1B5732BB618A2',
 PROPERTY                       TYPE /BOBF/OBM_ASSOC_KEY VALUE 'A6543B64103C1FE0A7E1B5732BB718A2',
      END OF ZI_SD_ITEMS_NEW,
      BEGIN OF ZI_SD_ITEMS_NEW_LOCK,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE 'A6543B64103C1FE0A7E1B5732BB898A2',
      END OF ZI_SD_ITEMS_NEW_LOCK,
      BEGIN OF ZI_SD_ITEMS_NEW_MESSAGE,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE 'A6543B64103C1FE0A7E1B5732BB878A2',
      END OF ZI_SD_ITEMS_NEW_MESSAGE,
      BEGIN OF ZI_SD_ITEMS_NEW_PROPERTY,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE 'A6543B64103C1FE0A7E1B5732BB8B8A2',
      END OF ZI_SD_ITEMS_NEW_PROPERTY,
    END OF SC_ASSOCIATION .
  constants:
    BEGIN OF SC_ASSOCIATION_ATTRIBUTE,
      BEGIN OF ZI_SD_ITEMS_NEW,
        BEGIN OF PROPERTY,
 ALL_NODE_PROPERTY              TYPE STRING VALUE 'ALL_NODE_PROPERTY',
 ALL_NODE_ATTRIBUTE_PROPERTY    TYPE STRING VALUE 'ALL_NODE_ATTRIBUTE_PROPERTY',
 ALL_ASSOCIATION_PROPERTY       TYPE STRING VALUE 'ALL_ASSOCIATION_PROPERTY',
 ALL_ASSOCIATION_ATTRIBUTE_PROP TYPE STRING VALUE 'ALL_ASSOCIATION_ATTRIBUTE_PROP',
 ALL_ACTION_PROPERTY            TYPE STRING VALUE 'ALL_ACTION_PROPERTY',
 ALL_ACTION_ATTRIBUTE_PROPERTY  TYPE STRING VALUE 'ALL_ACTION_ATTRIBUTE_PROPERTY',
 ALL_QUERY_PROPERTY             TYPE STRING VALUE 'ALL_QUERY_PROPERTY',
 ALL_QUERY_ATTRIBUTE_PROPERTY   TYPE STRING VALUE 'ALL_QUERY_ATTRIBUTE_PROPERTY',
 ALL_SUBTREE_PROPERTY           TYPE STRING VALUE 'ALL_SUBTREE_PROPERTY',
        END OF PROPERTY,
      END OF ZI_SD_ITEMS_NEW,
    END OF SC_ASSOCIATION_ATTRIBUTE .
  constants:
    SC_BO_KEY  TYPE /BOBF/OBM_BO_KEY VALUE 'A6543B64103C1FE0A7E1B5732BB578A2' .
  constants:
    SC_BO_NAME TYPE /BOBF/OBM_NAME VALUE 'ZI_SD_ITEMS_NEW' .
  constants:
    BEGIN OF SC_DETERMINATION,
      BEGIN OF ZI_SD_ITEMS_NEW,
 ACTION_AND_FIELD_CONTROL       TYPE /BOBF/DET_KEY VALUE 'A6543B64103C1FE0A7E1B5732BB938A2',
      END OF ZI_SD_ITEMS_NEW,
    END OF SC_DETERMINATION .
  constants:
    BEGIN OF SC_GROUP,
 ZI_SD_ITEMS_NEW                TYPE /BOBF/OBM_GROUP_KEY VALUE 'A6543B64103C1FE0A7E1B578EB21F8A2',
    END OF SC_GROUP .
  constants:
    SC_MODEL_VERSION TYPE /BOBF/CONF_VERSION VALUE '00000' .
  constants:
    BEGIN OF SC_NODE,
 ZI_SD_ITEMS_NEW                TYPE /BOBF/OBM_NODE_KEY VALUE 'A6543B64103C1FE0A7E1B5732BB5B8A2',
 ZI_SD_ITEMS_NEW_LOCK           TYPE /BOBF/OBM_NODE_KEY VALUE 'A6543B64103C1FE0A7E1B5732BB638A2',
 ZI_SD_ITEMS_NEW_MESSAGE        TYPE /BOBF/OBM_NODE_KEY VALUE 'A6543B64103C1FE0A7E1B5732BB5F8A2',
 ZI_SD_ITEMS_NEW_PROPERTY       TYPE /BOBF/OBM_NODE_KEY VALUE 'A6543B64103C1FE0A7E1B5732BB6F8A2',
    END OF SC_NODE .
  constants:
    BEGIN OF SC_NODE_ATTRIBUTE,
      BEGIN OF ZI_SD_ITEMS_NEW,
  NODE_DATA                      TYPE STRING VALUE 'NODE_DATA',
  VBELN                          TYPE STRING VALUE 'VBELN',
  POSNR                          TYPE STRING VALUE 'POSNR',
  MATNR                          TYPE STRING VALUE 'MATNR',
  LOCID                          TYPE STRING VALUE 'LOCID',
  QTY                            TYPE STRING VALUE 'QTY',
  PRICE                          TYPE STRING VALUE 'PRICE',
  CURRENCY                       TYPE STRING VALUE 'CURRENCY',
  VAL_ITEM                       TYPE STRING VALUE 'VAL_ITEM',
  DESC_IT                        TYPE STRING VALUE 'DESC_IT',
  VAL_LIQ_ITEM                   TYPE STRING VALUE 'VAL_LIQ_ITEM',
      END OF ZI_SD_ITEMS_NEW,
    END OF SC_NODE_ATTRIBUTE .
  constants:
    BEGIN OF SC_NODE_CATEGORY,
      BEGIN OF ZI_SD_ITEMS_NEW,
 ROOT                           TYPE /BOBF/OBM_NODE_CAT_KEY VALUE 'A6543B64103C1FE0A7E1B5732BB5D8A2',
      END OF ZI_SD_ITEMS_NEW,
    END OF SC_NODE_CATEGORY .
  constants:
    BEGIN OF SC_VALIDATION,
      BEGIN OF ZI_SD_ITEMS_NEW,
 ALTKEY_UNIQUENESS_CHECK        TYPE /BOBF/VAL_KEY VALUE 'A6543B64103C1FE0A7E1B5732BB998A2',
      END OF ZI_SD_ITEMS_NEW,
    END OF SC_VALIDATION .
endinterface.
